baseURL = "https://nippo.yagi2.com/"
languageCode = "ja-jp"
title = "日報"
theme = "one"
hasCJKLanguage = true
googleAnalytics="UA-28203375-10"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
  navigation = ["archives.md"]