baseURL = "https://nippo.yagi2.com"
languageCode = "ja"
title = "日報"
theme = "one"
googleAnalytics="UA-28203375-10"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
  navigation = ["archives.md"]