version: 2

jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:latest
    parallelism: 4
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: |
          git submodule sync
          git submodule update
          HUGO_ENV=production hugo -v -s ~/project/
          ls -la public/posts/