version: 2

jobs:
  checkout_code:
    machine:
      enabled: true
    working_directory: ~/hugo
    steps:
      - checkout
      - run: |
          git submodule sync
          git submodule update
      - save_cache:
          key: hugo-cache-{{ epoch }}
          paths:
            - ~/hugo

  build:
    docker:
      - image: june29/golang-hugo
    working_directory: ~/hugo
    steps:
      - restore_cache:
          key: hugo-cache
      - run:
          command: |
            hugo -v
            ls -la public/posts/
      - save_cache:
          key: hugo-cache-public-{{ epoch }}
          paths:
            - ~/hugo/public

  deploy:
    machine:
      enabled: true
    working_directory: ~/hugo
    steps:
      - restore_cache:
          key: hugo-cache-public
      - run:
          command: |
            aws s3 sync public s3://$S3_BACKET
            aws cloudfront create-invalidation --distribution-id $CF_DIST_1 --paths "/*" > /dev/null 2>&1
            aws cloudfront create-invalidation --distribution-id $CF_DIST_2 --paths "/*" > /dev/null 2>&1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build